# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[package]
name = "zuuliwarp"
version = "0.1.0"
edition = "2021"

[lib]
name = "zuuliwarp"
crate-type = ["cdylib"]

[dependencies]

[workspace]
